RUN_LIST = [
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre1.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post1.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post1_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre2.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post2.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post2_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre3.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post3.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post3_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre4.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post4.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post4_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre5.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post5.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post5_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre6.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post6.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post6_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre7.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post7.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post7_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre8.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post8.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post8_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre9.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post9.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post9_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre10.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post10.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post10_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre11.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post11.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post11_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre12.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post12.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post12_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre13.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post13.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post13_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre14.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post14.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post14_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
    {
        "pre": r"C:\\Users\\user\\Downloads\\im\\pre15.png",
        "post": r"C:\\Users\\user\\Downloads\\im\\post15.png",
        "mask": r"C:\\Users\\user\\Downloads\\im\\post15_mask.png",
        "gsd": 0.3,
        "structure_type": "Residential Low Rise",
    },
]